# input configs
samples:                                  metadata/samples_small.csv
variant_calls:                            metadata/variant_calls_small.csv
deduplicated_variants_output_folder:      sample_data/pangenome_variations/output_pangenome_variations_small
data_from_paper:                          False


# output configs
output_folder:                            analysis_output_small_with_filters
variant_calls_flank_length_for_precision: 150
max_gt_conf_percentile:                   11
step_gt_conf_percentile:                  5


# filtering configs
coverage_filters:                         [90]
strand_bias_filters:                      [0.2]
gaps_filters:                             [0.5]
