samples:                    metadata/samples.csv
variant_calls:              metadata/variant_calls.csv
variant_calls_probe_length: 25
truth_probes_flank_length:  21
#coverage_filters:           [0, 1, 2, 5, 7, 10]
#strand_bias_filters:        [0.0, 0.01, 0.02, 0.05, 0.10, 0.20]
#gaps_filters:               [1.0, 0.9, 0.8, 0.7, 0.6, 0.5]
coverage_filters:           [0]
strand_bias_filters:        [0.0]
gaps_filters:               [1.0]