pandora_executable: /hps/nobackup/iqbal/leandro/pandora_compare/build_release/pandora
git_commit: d2dd228
PRGs: [sample_data/ecoli_pangenome_PRG_050319.100_first_genes.fa, sample_data/ecoli_pangenome_PRG_050319.100_first_genes.copy.fa]
window_size: 19
kmer_size: 31
#threads: [1, 2, 4, 8, 16]
threads: [16]
outdir: analysis