git_commit: ed953d1
window_size: 19
kmer_size: 31
#threads: [1, 2, 4, 8, 16]
threads: [1, 2]
benchmark_repeat_times: 1

# TODO: improve this with csv files
data_folder: sample_data/
PRGs: [prg1.fa, prg2.fa]
reads_to_map: [reads1.fq, reads2.fq]
