$schema:                        "http://json-schema.org/draft-07/schema#"

description:                    snakemake configuration file

type:                           object

properties:
    output_folder:
        type:                   string
        description:            Path to the output folder
    samples:
        type:                   string
        description:            Path to CSV file containing the samples information.
    variant_calls:
        type:                   string
        description:            Path to CSV file containing the variant calls information.
    variant_calls_probe_length:
        type:                   number
        description:            The flank length to use for variant calls.
    truth_probes_flank_length:
        type:                   number
        description:            The flank length to use for truth calls.
    number_of_points_in_ROC_curve:
        type:                   number
        description:            Number of points to plot in the ROC curve. The higher, the better, but it is also slower.
        default:                1000
    coverage_filters:
        type:                   array
        description:            VCF records having mean coverage smaller than this value will be filtered out from the analysis. One plot is produced for each value.
        items:
            type:               number
    strand_bias_filters:
        type:                   array
        description:            VCF records having a strand coverage ratio smaller than this value will be filtered out from the analysis. One plot is produced for each value.
        items:
            type:               number
    gaps_filters:
        type:                   array
        description:            VCF records having a gaps fractions larger than this value will be filtered out from the analysis. One plot is produced for each value.
        items:
            type:               number


required:
  - samples
  - variant_calls
  - variant_calls_probe_length
  - truth_probes_flank_length
  - coverage_filters
  - strand_bias_filters
  - gaps_filters