$schema:                        "http://json-schema.org/draft-07/schema#"

description:                    snakemake configuration file

type:                           object

properties:
    samples:
        type:           string
        description:    Path to CSV file containing the samples information.
    variant_calls:
        type:           string
        description:    Path to CSV file containing the variant calls information.
    variant_calls_probe_length:
        type:           number
        description:    The flank length to use for variant calls.
    truth_calls_probe_length:
        type:           number
        description:    The flank length to use for truth calls.
    mem_mb:
        type:           array
        items: {
          type: number
        }



required:
  - samples
  - variant_calls
  - variant_calls_probe_length
  - truth_calls_probe_length
  - mem_mb